### ISSUE TITLE
Error validating self signed certificate

### ISSUE THREAD

**Issue by txeli** [kevinoid/auth-mailbox-joomla#11]
Hello.

I'm trying to use the plugin in a Joomla 3.4.8 site with a postfix mail server using starttls encryption and a self signed certificate. Every time I try to login I get this error message:

"Certificate failure for "myimapserver": self signed certificate: /C=AU/ST=Some-State/O=Internet Widgits Pt"

Any solution to this?
Thanks

**Comment by txeli** [comment]
Hello again.

Checking my mail server log I realized that I was sending twice domain name "user@domain.com@domain.com"
Actually there isn't any problem, sorry.

**Comment by kevinoid** [comment]
No worries.  Glad you were able to figure it out!
